### ISSUE TITLE
上传PDF，回调POST时报错

### ISSUE THREAD

**Issue by destinyd** [mindpin/file-part-upload#12]
```
Started POST "/bank/file_part_upload/file_entities" for 183.136.139.17 at 2016-01-13 11:04:33 +0800
Processing by FilePartUpload::FileEntitiesController#create as HTML
  Parameters: {"bucket"=>"ddtest", "token"=>"kc/n4JjbAEs.pdf", "file_size"=>"97152", "image_rgb"=>"", "original"=>"1.pdf", "mime"=>"application/pdf", "image_width"=>"0", "image_height"=>"0", "avinfo_format"=>"", "avinfo_total_bit_rate"=>"", "avinfo_total_duration"=>"", "avinfo_video_codec_name"=>"", "avinfo_video_bit_rate"=>"", "avinfo_video_duration"=>"", "avinfo_height"=>"", "avinfo_width"=>"", "avinfo_audio_codec_name"=>"", "avinfo_audio_bit_rate"=>"", "avinfo_audio_duration"=>""}
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.4450ms
  MOPED: 127.0.0.1:27017 INSERT       database=knowledge-camp-development collection=file_part_upload_file_entities documents=[{"_id"=>BSON::ObjectId('5695bec163686513780a0000'), "original"=>"1.pdf", "token"=>"kc/n4JjbAEs.pdf", "mime"=>"application/pdf", "meta"=>{"file_size"=>97152}, "merged"=>false, "kind"=>"pdf", "updated_at"=>2016-01-13 03:04:33 UTC, "created_at"=>2016-01-13 03:04:33 UTC}] flags=[]
                         COMMAND      database=knowledge-camp-development command={:getlasterror=>1, :w=>1} runtime: 0.3380ms
Completed 500 Internal Server Error in 1040ms (Elasticsearch: 0.0ms)

JSON::ParserError (757: unexpected token at '%PDF-1.5
%����
1 0 obj
[/PDF/ImageB/ImageC/ImageI/Text]
endobj
4 0 obj
<</Length 5 0 R
/Filter/FlateDecode
>>
stream
���nVꄌ���!� �sȲ!���dE��"(DXoޔ��{��U׫��LW�$�˰[o�����������K�_�^⬾� ���nx�(L�g\��8
                                                                                ~9�
�%U�v�|��8�"��:���                                                                  #��;pFk�H��8~�
,���?Lw�/6�蔎������
                   }�ɭ���0-�N�.<Η��n7�z�S=��e��P6�1�1���}   Ņ��M+��/�B��^oB�|��A�S�h䠵�I��<�� a>�!pHrfw�$�zI��8�U_zҥ���
                                                                                                                           ���3!�f̿r�C�ڋ���r`�,�����B���\O3'v>�/T�
��l~^�Q^1��T��MC�i~/����Tۇ'0   ��O�]�^�gZ������-Fbm���1�|��
�j�ȅ<�RϡA�c�j   �AJ�� �t �z�s{�_�x*�������Sٵ/��s��S!7w���w�Ky����ś7�.T�%��g���E�p����E����ǩ!J}]��5D��VA_�L;IE5Dc��L$E�e�iF����'):
  json (1.8.3) lib/json/common.rb:155:in `parse'
  json (1.8.3) lib/json/common.rb:155:in `parse'
  /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/file-part-upload-6898ae1f53b6/lib/file_part_upload/qiniu_methods.rb:171:in `update_page_count_by_pdf_url'
  /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/file-part-upload-6898ae1f53b6/lib/file_part_upload/qiniu_methods.rb:165:in `put_pdf_transcode_to_quene'
  /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/file-part-upload-6898ae1f53b6/lib/file_part_upload/qiniu_methods.rb:20:in `process_transcode'
  activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:226:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:226:in `block in halting_and_conditional'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  mongoid (4.0.0) lib/mongoid/interceptable.rb:138:in `run_callbacks'
  mongoid (4.0.0) lib/mongoid/persistable/creatable.rb:116:in `block in prepare_insert'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  mongoid (4.0.0) lib/mongoid/interceptable.rb:138:in `run_callbacks'
  mongoid (4.0.0) lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
  mongoid (4.0.0) lib/mongoid/persistable/creatable.rb:23:in `insert'
  mongoid (4.0.0) lib/mongoid/persistable/creatable.rb:179:in `block in create!'
  mongoid (4.0.0) lib/mongoid/threaded/lifecycle.rb:156:in `_creating'
  mongoid (4.0.0) lib/mongoid/persistable/creatable.rb:174:in `create!'
  /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/file-part-upload-6898ae1f53b6/lib/file_part_upload/qiniu_create_methods.rb:35:in `from_qiniu_callback_body'
  /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/file-part-upload-6898ae1f53b6/lib/file_part_upload/qiniu_controller_methods.rb:40:in `create'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/DD/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/DD/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/DD/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (6.3ms)
  Rendered /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.3ms)
  Rendered /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
  Rendered /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (75.0ms)
```

**Comment by destinyd** [comment]
[1.pdf](https://github.com/mindpin/file-part-upload/files/88305/1.pdf)

**Comment by destinyd** [comment]
七牛需要开通PDF转换服务即可
